version: '3'
services:
  app1:
    image: flask-app
    ports:
      - "5000:5000"
    networks:
      - my-network
  app2:
    image: flask-app
    ports:
      - "5001:5000"
    networks:
      - my-network
networks:
  my-network:
